# Generated by Django 4.2.16 on 2026-09-06 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('date_filed', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('fraud_flag', models.BooleanField(default=False)),
                ('fraud_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='policies.policy')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claims_claim',
                'ordering': ['-date_filed'],
                'indexes': [models.Index(fields=['status'], name='claims_clai_status_b4f911_idx'), models.Index(fields=['fraud_flag', 'status'], name='claims_clai_fraud_f_47b2e1_idx')],
            },
        ),
    ]
