# Generated by Django 4.2.16 on 2026-09-06 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('policy_type', models.CharField(choices=[('auto', 'Auto'), ('health', 'Health'), ('property', 'Property')], max_length=20)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('pending_activation', 'Pending Activation'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending_activation', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policies_policy',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['policy_number'], name='policies_po_policy__a03f9f_idx')],
            },
        ),
    ]
